//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct Today {


        public struct Table {


            public struct Label {

                /// Base translation: Error
                public static var Error : String = NSLocalizedString("Today.Table.Label.Error", comment: "")

                /// Base translation: Loading...
                public static var Loading : String = NSLocalizedString("Today.Table.Label.Loading", comment: "")

                /// Base translation: Tap to refresh
                public static var Taptorefresh : String = NSLocalizedString("Today.Table.Label.TapToRefresh", comment: "")

            }
        }

        public struct Cell {


            public struct Label {

                /// Base translation: Total
                public static var Total : String = NSLocalizedString("Today.Cell.Label.Total", comment: "")

                /// Base translation: Available
                public static var Available : String = NSLocalizedString("Today.Cell.Label.Available", comment: "")

                /// Base translation: --
                public static var Nodata : String = NSLocalizedString("Today.Cell.Label.NoData", comment: "")

                /// Base translation: Occupied
                public static var Used : String = NSLocalizedString("Today.Cell.Label.Used", comment: "")

            }
        }

        public struct Main {


            public struct Label {

                /// Base translation: Science Campus:
                public static var Sciencecampus : String = NSLocalizedString("Today.Main.Label.ScienceCampus", comment: "")

                /// Base translation: --
                public static var Nodata : String = NSLocalizedString("Today.Main.Label.NoData", comment: "")

                /// Base translation: Liberal Art Campus:
                public static var Liberalartcampus : String = NSLocalizedString("Today.Main.Label.LiberalArtCampus", comment: "")

                /// Base translation: %@ studying
                public static func Studying(_ value1 : String) -> String {
                    return String(format: NSLocalizedString("Today.Main.Label.Studying", comment: ""), value1)
                }

            }
        }
    }
}