//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct Kustudy {


        public struct Today {

            /// Base translation: Total
            public static var Total : String = NSLocalizedString("kuStudy.Today.Total", comment: "")

            /// Base translation: Error
            public static var Error : String = NSLocalizedString("kuStudy.Today.Error", comment: "")

            /// Base translation: Tap to refresh
            public static var Taptorefresh : String = NSLocalizedString("kuStudy.Today.TapToRefresh", comment: "")

            /// Base translation: Liberal Art Campus
            public static var Liberalartcampus : String = NSLocalizedString("kuStudy.Today.LiberalArtCampus", comment: "")

            /// Base translation: Updated: 
            public static var Updated : String = NSLocalizedString("kuStudy.Today.Updated", comment: "")

            /// Base translation: Available
            public static var Available : String = NSLocalizedString("kuStudy.Today.Available", comment: "")

            /// Base translation: Science Campus
            public static var Sciencecampus : String = NSLocalizedString("kuStudy.Today.ScienceCampus", comment: "")

            /// Base translation:  Studying
            public static var Studying : String = NSLocalizedString("kuStudy.Today.Studying", comment: "")

            /// Base translation: Occupied
            public static var Used : String = NSLocalizedString("kuStudy.Today.Used", comment: "")

            /// Base translation: Loading...
            public static var Loading : String = NSLocalizedString("kuStudy.Today.Loading", comment: "")

            /// Base translation: --
            public static var Emptydata : String = NSLocalizedString("kuStudy.Today.EmptyData", comment: "")

        }
    }
}