//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct Table {


        public struct Label {

            /// Base translation: Failed to load information.
            public static var Error : String = NSLocalizedString("Table.Label.Error", comment: "")

            /// Base translation: Tap to refresh
            public static var TapToRefresh : String = NSLocalizedString("Table.Label.TapToRefresh", comment: "")

            /// Base translation: Loading...
            public static var Loading : String = NSLocalizedString("Table.Label.Loading", comment: "")

        }
    }

    public struct Main {


        public struct Label {

            /// Base translation: Science Campus:
            public static var ScienceCampus : String = NSLocalizedString("Main.Label.ScienceCampus", comment: "")

            /// Base translation: Liberal Art Campus:
            public static var LiberalArtCampus : String = NSLocalizedString("Main.Label.LiberalArtCampus", comment: "")

            /// Base translation: --
            public static var NoData : String = NSLocalizedString("Main.Label.NoData", comment: "")

            /// Base translation: %@ studying
            public static func Studying(_ value1 : String) -> String {
                return String(format: NSLocalizedString("Main.Label.Studying", comment: ""), value1)
            }

        }
    }

    public struct Cell {


        public struct Label {

            /// Base translation: Total
            public static var Total : String = NSLocalizedString("Cell.Label.Total", comment: "")

            /// Base translation: Available
            public static var Available : String = NSLocalizedString("Cell.Label.Available", comment: "")

            /// Base translation: --
            public static var NoData : String = NSLocalizedString("Cell.Label.NoData", comment: "")

            /// Base translation: Occupied
            public static var Used : String = NSLocalizedString("Cell.Label.Used", comment: "")

        }
    }
}