# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"

default_platform :ios

platform :ios do
  before_all do
    
  end

  lane :update_version_major do
  increment_version_number(bump_type: "major")
    increment_build_number
  end

  lane :update_version_minor do
    increment_version_number(bump_type: "minor")
    increment_build_number
  end

  lane :update_version_patch do
    increment_version_number(bump_type: "patch")
    increment_build_number
  end

  lane :update_build_number do
    increment_build_number
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    cocoapods
    gym(scheme: "kuStudy")
    pilot
    # sh "your_script.sh"
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    cocoapods
    gym(scheme: "kuStudy")
    snapshot
    # frameit
    deliver(force: true)
  end

  after_all do |lane|
    
  end

  error do |lane, exception|
    
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
