
fastlane_version "1.101.0"

default_platform :ios

platform :ios do
  before_all do
    
  end

  lane :update_version_major do
    increment_version_number(bump_type: "major", xcodeproj: "./kuStudy/kuStudy.xcodeproj")
  end

  lane :update_version_minor do
    increment_version_number(bump_type: "minor", xcodeproj: "./kuStudy/kuStudy.xcodeproj")
  end

  lane :update_version_patch do
    increment_version_number(bump_type: "patch", xcodeproj: "./kuStudy/kuStudy.xcodeproj")
  end

  lane :update_build_number do
    increment_build_number(xcodeproj: "./kuStudy/kuStudy.xcodeproj")
  end

  desc "Generate Localization file"
  lane :localize do
  	sh "cd .. && wget -O LaurineGenerator.swift https://raw.githubusercontent.com/JiriTrecak/Laurine/master/LaurineGenerator.swift"
  	sh "cd .. && ./LaurineGenerator.swift -i ./kuStudy/kuStudy/Base.lproj/Localizable.strings -c -o ./kuStudy/kuStudy/Localizations.swift"
  	sh "cd .. && ./LaurineGenerator.swift -i \"./kuStudy/kuStudy\ Today\ Extension/Base.lproj/Localizable.strings\" -c -o \"./kuStudy/kuStudy\ Today\ Extension/Localizations.swift\""
  	sh "cd .. && ./LaurineGenerator.swift -i \"./kuStudy/kuStudy\ WatchKit\ Extension/Base.lproj/Localizable.strings\" -c -o \"./kuStudy/kuStudy\ WatchKit\ Extension/Localizations.swift\""
  end

  desc "Runs all the tests"
  lane :test do
    scan
    notification(subtitle: "🚀 Fastlane done!", message: "Ran all tests.")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    xcode_select "/Applications/Xcode-beta.app"

    # Check & Badge
    ensure_git_status_clean
    badge(dark: true)

    # Upload
    cocoapods
    gym(scheme: "kuStudy")
    # pilot

    # Reset
    reset_git_repo
    cocoapods

    # Tag
    # version = "#{get_version_number}.#{get_build_number}"
    # add_git_tag(tag: version)

    # Increase build number
    # increment_build_number
    # commit_version_bump(message: "Increased build number.")

    notification(subtitle: "🚀 Fastlane done!", message: "Uploaded to TestFlight.")
  end

  desc "Deploy a new version to the App Store"
  lane :store do
    ensure_git_status_clean
    cocoapods
    gym(scheme: "kuStudy")
    deliver(skip_metadata: true, skip_screenshots: true)

    # Increase build number
    increment_build_number(xcodeproj: "./kuStudy/kuStudy.xcodeproj")
    commit_version_bump(message: "Increased build number.")

    notification(subtitle: "🚀 Fastlane done!", message: "Uploaded to App Store.")
  end

  desc "A new release"
  lane :release do
    ensure_git_status_clean
    cocoapods
    gym(scheme: "kuStudy")
    snapshot
    deliver

    # Increase build number
    increment_build_number(xcodeproj: "./kuStudy/kuStudy.xcodeproj")
    commit_version_bump(message: "Increased build number.")

    notification(subtitle: "🚀 Fastlane done!", message: "Uploaded to App Store.")
  end

  after_all do |lane|
    
  end

  error do |lane, exception|
    notification(
      subtitle: "Fastlane failed 😭.",
      message: exception.message
    )
  end
end
