# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone SE",
  "iPad Retina",
  "iPad Pro (12.9-inch)"
])

languages([
  "en-US",
  "ko"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme "kuStudy Snapshot"

output_directory "./fastlane/screenshots"
clear_previous_screenshots true

# Choose which project/workspace to use
# project "./kuStudy/kuStudy.xcodeproj"
workspace "./kuStudy.xcworkspace"
