workspace "./kuStudy.xcworkspace"
scheme "kuStudy Snapshot"

output_directory "./fastlane/screenshots"
clear_previous_screenshots true
# erase_simulator true
localize_simulator true
# clean true
reinstall_app true

languages([
  "en-US",
  "ko"
])

devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X",
  "iPad Pro (9.7-inch)",
  "iPad Pro (12.9-inch)"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])
