# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone SE",
  "iPad Pro (9.7 inch)",
  "iPad Pro (12.9 inch)"
])

languages([
  "en-US",
  "ko"
])

output_directory "./fastlane/screenshots"
clear_previous_screenshots true

workspace "./kuStudy.xcworkspace"
scheme "kuStudy Snapshot"

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

erase_simulator true
localize_simulator true
clean true
reinstall_app true
