//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct Label {

        /// Base translation: Total
        public static var Total : String = NSLocalizedString("Label.Total", comment: "")

        /// Base translation: Available
        public static var Available : String = NSLocalizedString("Label.Available", comment: "")

        /// Base translation: Occupied
        public static var Used : String = NSLocalizedString("Label.Used", comment: "")

        /// Base translation:  Studying
        public static var StudyingDescription : String = NSLocalizedString("Label.StudyingDescription", comment: "")

    }

    public struct Cell {


        public struct Label {

            /// Base translation: Total
            public static var Total : String = NSLocalizedString("Cell.Label.Total", comment: "")

            /// Base translation: Occupied
            public static var Used : String = NSLocalizedString("Cell.Label.Used", comment: "")

            /// Base translation: Available
            public static var Available : String = NSLocalizedString("Cell.Label.Available", comment: "")

        }
    }

    public struct Complication {

        /// Base translation: Total: 
        public static var Total : String = NSLocalizedString("Complication.Total", comment: "")

        /// Base translation: Available: 
        public static var Available : String = NSLocalizedString("Complication.Available", comment: "")

    }
}