//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct Watch {


        public struct Cell {


            public struct Label {

                /// Base translation: Total
                public static var Total : String = NSLocalizedString("Watch.Cell.Label.Total", comment: "")

                /// Base translation: Occupied
                public static var Used : String = NSLocalizedString("Watch.Cell.Label.Used", comment: "")

                /// Base translation: Available
                public static var Available : String = NSLocalizedString("Watch.Cell.Label.Available", comment: "")

            }
        }

        public struct Label {

            /// Base translation: Total
            public static var Total : String = NSLocalizedString("Watch.Label.Total", comment: "")

            /// Base translation: Available
            public static var Available : String = NSLocalizedString("Watch.Label.Available", comment: "")

            /// Base translation: Occupied
            public static var Used : String = NSLocalizedString("Watch.Label.Used", comment: "")

            /// Base translation:  Studying
            public static var Studyingdescription : String = NSLocalizedString("Watch.Label.StudyingDescription", comment: "")

        }

        public struct Complication {

            /// Base translation: Total: 
            public static var Total : String = NSLocalizedString("Watch.Complication.Total", comment: "")

            /// Base translation: Available: 
            public static var Available : String = NSLocalizedString("Watch.Complication.Available", comment: "")

        }
    }
}